/**
 * This file is automatically generated by `yarn generate-classes`.
 * DO NOT MANUALLY EDIT IT OR YOUR CHANGES WILL BE LOST!
 */

import { Annotator } from "./../exporting/Annotator";
import { Axis } from "./../../charts/xy/axes/Axis";
import { AxisBullet } from "./../../charts/xy/axes/AxisBullet";
import { AxisLabel } from "./../../charts/xy/axes/AxisLabel";
import { AxisLabelRadial } from "./../../charts/xy/axes/AxisLabelRadial";
import { AxisRenderer } from "./../../charts/xy/axes/AxisRenderer";
import { AxisRendererCircular } from "./../../charts/radar/AxisRendererCircular";
import { AxisRendererRadial } from "./../../charts/radar/AxisRendererRadial";
import { AxisRendererX } from "./../../charts/xy/axes/AxisRendererX";
import { AxisRendererY } from "./../../charts/xy/axes/AxisRendererY";
import { AxisTick } from "./../../charts/xy/axes/AxisTick";
import { BaseColumnSeries } from "./../../charts/xy/series/BaseColumnSeries";
import { BreadcrumbBar } from "./../../charts/hierarchy/BreadcrumbBar";
import { Bullet } from "./../../core/render/Bullet";
import { Button } from "./../../core/render/Button";
import { Candlestick } from "./../../charts/xy/series/Candlestick";
import { CandlestickSeries } from "./../../charts/xy/series/CandlestickSeries";
import { CategoryAxis } from "./../../charts/xy/axes/CategoryAxis";
import { CategoryDateAxis } from "./../../charts/xy/axes/CategoryDateAxis";
import { Chart } from "./../../core/render/Chart";
import { Chord } from "./../../charts/flow/Chord";
import { ChordDirected } from "./../../charts/flow/ChordDirected";
import { ChordLink } from "./../../charts/flow/ChordLink";
import { ChordLinkDirected } from "./../../charts/flow/ChordLinkDirected";
import { ChordNodes } from "./../../charts/flow/ChordNodes";
import { ChordNonRibbon } from "./../../charts/flow/ChordNonRibbon";
import { Circle } from "./../../core/render/Circle";
import { CirclePattern } from "./../../core/render/patterns/CirclePattern";
import { ClockHand } from "./../../charts/radar/ClockHand";
import { ColorSet } from "./../../core/util/ColorSet";
import { ColumnSeries } from "./../../charts/xy/series/ColumnSeries";
import { Component } from "./../../core/render/Component";
import { Container } from "./../../core/render/Container";
import { DateAxis } from "./../../charts/xy/axes/DateAxis";
import { DurationAxis } from "./../../charts/xy/axes/DurationAxis";
import { Ellipse } from "./../../core/render/Ellipse";
import { Entity } from "./../../core/util/Entity";
import { Exporting } from "./../exporting/Exporting";
import { ExportingMenu } from "./../exporting/ExportingMenu";
import { Flow } from "./../../charts/flow/Flow";
import { FlowLink } from "./../../charts/flow/FlowLink";
import { FlowNode } from "./../../charts/flow/FlowNode";
import { FlowNodes } from "./../../charts/flow/FlowNodes";
import { ForceDirected } from "./../../charts/hierarchy/ForceDirected";
import { FunnelSeries } from "./../../charts/funnel/FunnelSeries";
import { FunnelSlice } from "./../../charts/funnel/FunnelSlice";
import { GaplessDateAxis } from "./../../charts/xy/axes/GaplessDateAxis";
import { Gradient } from "./../../core/render/gradients/Gradient";
import { Graphics } from "./../../core/render/Graphics";
import { GraticuleSeries } from "./../../charts/map/GraticuleSeries";
import { Grid } from "./../../charts/xy/axes/Grid";
import { GridLayout } from "./../../core/render/GridLayout";
import { HeatLegend } from "./../../core/render/HeatLegend";
import { Hierarchy } from "./../../charts/hierarchy/Hierarchy";
import { HierarchyLink } from "./../../charts/hierarchy/HierarchyLink";
import { HierarchyNode } from "./../../charts/hierarchy/HierarchyNode";
import { HorizontalLayout } from "./../../core/render/HorizontalLayout";
import { InterfaceColors } from "./../../core/util/InterfaceColors";
import { Label } from "./../../core/render/Label";
import { Layout } from "./../../core/render/Layout";
import { Legend } from "./../../core/render/Legend";
import { Line } from "./../../core/render/Line";
import { LinePattern } from "./../../core/render/patterns/LinePattern";
import { LineSeries } from "./../../charts/xy/series/LineSeries";
import { LinearGradient } from "./../../core/render/gradients/LinearGradient";
import { LinkedHierarchy } from "./../../charts/hierarchy/LinkedHierarchy";
import { LinkedHierarchyNode } from "./../../charts/hierarchy/LinkedHierarchyNode";
import { MapChart } from "./../../charts/map/MapChart";
import { MapLine } from "./../../charts/map/MapLine";
import { MapLineSeries } from "./../../charts/map/MapLineSeries";
import { MapPointSeries } from "./../../charts/map/MapPointSeries";
import { MapPolygon } from "./../../charts/map/MapPolygon";
import { MapPolygonSeries } from "./../../charts/map/MapPolygonSeries";
import { MapSeries } from "./../../charts/map/MapSeries";
import { Modal } from "./../../core/util/Modal";
import { OHLC } from "./../../charts/xy/series/OHLC";
import { OHLCSeries } from "./../../charts/xy/series/OHLCSeries";
import { Pack } from "./../../charts/hierarchy/Pack";
import { Partition } from "./../../charts/hierarchy/Partition";
import { Pattern } from "./../../core/render/patterns/Pattern";
import { PercentChart } from "./../../charts/percent/PercentChart";
import { PercentSeries } from "./../../charts/percent/PercentSeries";
import { PictorialStackedSeries } from "./../../charts/funnel/PictorialStackedSeries";
import { Picture } from "./../../core/render/Picture";
import { PieChart } from "./../../charts/pie/PieChart";
import { PieSeries } from "./../../charts/pie/PieSeries";
import { PointedRectangle } from "./../../core/render/PointedRectangle";
import { PyramidSeries } from "./../../charts/funnel/PyramidSeries";
import { RadarChart } from "./../../charts/radar/RadarChart";
import { RadarColumnSeries } from "./../../charts/radar/RadarColumnSeries";
import { RadarCursor } from "./../../charts/radar/RadarCursor";
import { RadarLineSeries } from "./../../charts/radar/RadarLineSeries";
import { RadialGradient } from "./../../core/render/gradients/RadialGradient";
import { RadialLabel } from "./../../core/render/RadialLabel";
import { RadialText } from "./../../core/render/RadialText";
import { Rectangle } from "./../../core/render/Rectangle";
import { RectanglePattern } from "./../../core/render/patterns/RectanglePattern";
import { RoundedRectangle } from "./../../core/render/RoundedRectangle";
import { Sankey } from "./../../charts/flow/Sankey";
import { SankeyLink } from "./../../charts/flow/SankeyLink";
import { SankeyNodes } from "./../../charts/flow/SankeyNodes";
import { Scrollbar } from "./../../core/render/Scrollbar";
import { SerialChart } from "./../../core/render/SerialChart";
import { Series } from "./../../core/render/Series";
import { Slice } from "./../../core/render/Slice";
import { SliceGrouper } from "./../sliceGrouper/SliceGrouper";
import { SlicedChart } from "./../../charts/funnel/SlicedChart";
import { Slider } from "./../../core/render/Slider";
import { SmoothedRadarLineSeries } from "./../../charts/radar/SmoothedRadarLineSeries";
import { SmoothedXLineSeries } from "./../../charts/xy/series/SmoothedXLineSeries";
import { SmoothedXYLineSeries } from "./../../charts/xy/series/SmoothedXYLineSeries";
import { SmoothedYLineSeries } from "./../../charts/xy/series/SmoothedYLineSeries";
import { Sprite } from "./../../core/render/Sprite";
import { Star } from "./../../core/render/Star";
import { StepLineSeries } from "./../../charts/xy/series/StepLineSeries";
import { Sunburst } from "./../../charts/hierarchy/Sunburst";
import { Text } from "./../../core/render/Text";
import { Tick } from "./../../core/render/Tick";
import { Tooltip } from "./../../core/render/Tooltip";
import { Tree } from "./../../charts/hierarchy/Tree";
import { Treemap } from "./../../charts/hierarchy/Treemap";
import { Triangle } from "./../../core/render/Triangle";
import { ValueAxis } from "./../../charts/xy/axes/ValueAxis";
import { Venn } from "./../../charts/venn/Venn";
import { VerticalLayout } from "./../../core/render/VerticalLayout";
import { WordCloud } from "./../../charts/wordcloud/WordCloud";
import { XYChart } from "./../../charts/xy/XYChart";
import { XYChartScrollbar } from "./../../charts/xy/XYChartScrollbar";
import { XYCursor } from "./../../charts/xy/XYCursor";
import { XYSeries } from "./../../charts/xy/series/XYSeries";
import { ZoomControl } from "./../../charts/map/ZoomControl";

export interface IClasses {
	"Annotator": typeof Annotator;
	"Axis": typeof Axis;
	"AxisBullet": typeof AxisBullet;
	"AxisLabel": typeof AxisLabel;
	"AxisLabelRadial": typeof AxisLabelRadial;
	"AxisRenderer": typeof AxisRenderer;
	"AxisRendererCircular": typeof AxisRendererCircular;
	"AxisRendererRadial": typeof AxisRendererRadial;
	"AxisRendererX": typeof AxisRendererX;
	"AxisRendererY": typeof AxisRendererY;
	"AxisTick": typeof AxisTick;
	"BaseColumnSeries": typeof BaseColumnSeries;
	"BreadcrumbBar": typeof BreadcrumbBar;
	"Bullet": typeof Bullet;
	"Button": typeof Button;
	"Candlestick": typeof Candlestick;
	"CandlestickSeries": typeof CandlestickSeries;
	"CategoryAxis": typeof CategoryAxis;
	"CategoryDateAxis": typeof CategoryDateAxis;
	"Chart": typeof Chart;
	"Chord": typeof Chord;
	"ChordDirected": typeof ChordDirected;
	"ChordLink": typeof ChordLink;
	"ChordLinkDirected": typeof ChordLinkDirected;
	"ChordNodes": typeof ChordNodes;
	"ChordNonRibbon": typeof ChordNonRibbon;
	"Circle": typeof Circle;
	"CirclePattern": typeof CirclePattern;
	"ClockHand": typeof ClockHand;
	"ColorSet": typeof ColorSet;
	"ColumnSeries": typeof ColumnSeries;
	"Component": typeof Component;
	"Container": typeof Container;
	"DateAxis": typeof DateAxis;
	"DurationAxis": typeof DurationAxis;
	"Ellipse": typeof Ellipse;
	"Entity": typeof Entity;
	"Exporting": typeof Exporting;
	"ExportingMenu": typeof ExportingMenu;
	"Flow": typeof Flow;
	"FlowLink": typeof FlowLink;
	"FlowNode": typeof FlowNode;
	"FlowNodes": typeof FlowNodes;
	"ForceDirected": typeof ForceDirected;
	"FunnelSeries": typeof FunnelSeries;
	"FunnelSlice": typeof FunnelSlice;
	"GaplessDateAxis": typeof GaplessDateAxis;
	"Gradient": typeof Gradient;
	"Graphics": typeof Graphics;
	"GraticuleSeries": typeof GraticuleSeries;
	"Grid": typeof Grid;
	"GridLayout": typeof GridLayout;
	"HeatLegend": typeof HeatLegend;
	"Hierarchy": typeof Hierarchy;
	"HierarchyLink": typeof HierarchyLink;
	"HierarchyNode": typeof HierarchyNode;
	"HorizontalLayout": typeof HorizontalLayout;
	"InterfaceColors": typeof InterfaceColors;
	"Label": typeof Label;
	"Layout": typeof Layout;
	"Legend": typeof Legend;
	"Line": typeof Line;
	"LinePattern": typeof LinePattern;
	"LineSeries": typeof LineSeries;
	"LinearGradient": typeof LinearGradient;
	"LinkedHierarchy": typeof LinkedHierarchy;
	"LinkedHierarchyNode": typeof LinkedHierarchyNode;
	"MapChart": typeof MapChart;
	"MapLine": typeof MapLine;
	"MapLineSeries": typeof MapLineSeries;
	"MapPointSeries": typeof MapPointSeries;
	"MapPolygon": typeof MapPolygon;
	"MapPolygonSeries": typeof MapPolygonSeries;
	"MapSeries": typeof MapSeries;
	"Modal": typeof Modal;
	"OHLC": typeof OHLC;
	"OHLCSeries": typeof OHLCSeries;
	"Pack": typeof Pack;
	"Partition": typeof Partition;
	"Pattern": typeof Pattern;
	"PercentChart": typeof PercentChart;
	"PercentSeries": typeof PercentSeries;
	"PictorialStackedSeries": typeof PictorialStackedSeries;
	"Picture": typeof Picture;
	"PieChart": typeof PieChart;
	"PieSeries": typeof PieSeries;
	"PointedRectangle": typeof PointedRectangle;
	"PyramidSeries": typeof PyramidSeries;
	"RadarChart": typeof RadarChart;
	"RadarColumnSeries": typeof RadarColumnSeries;
	"RadarCursor": typeof RadarCursor;
	"RadarLineSeries": typeof RadarLineSeries;
	"RadialGradient": typeof RadialGradient;
	"RadialLabel": typeof RadialLabel;
	"RadialText": typeof RadialText;
	"Rectangle": typeof Rectangle;
	"RectanglePattern": typeof RectanglePattern;
	"RoundedRectangle": typeof RoundedRectangle;
	"Sankey": typeof Sankey;
	"SankeyLink": typeof SankeyLink;
	"SankeyNodes": typeof SankeyNodes;
	"Scrollbar": typeof Scrollbar;
	"SerialChart": typeof SerialChart;
	"Series": typeof Series;
	"Slice": typeof Slice;
	"SliceGrouper": typeof SliceGrouper;
	"SlicedChart": typeof SlicedChart;
	"Slider": typeof Slider;
	"SmoothedRadarLineSeries": typeof SmoothedRadarLineSeries;
	"SmoothedXLineSeries": typeof SmoothedXLineSeries;
	"SmoothedXYLineSeries": typeof SmoothedXYLineSeries;
	"SmoothedYLineSeries": typeof SmoothedYLineSeries;
	"Sprite": typeof Sprite;
	"Star": typeof Star;
	"StepLineSeries": typeof StepLineSeries;
	"Sunburst": typeof Sunburst;
	"Text": typeof Text;
	"Tick": typeof Tick;
	"Tooltip": typeof Tooltip;
	"Tree": typeof Tree;
	"Treemap": typeof Treemap;
	"Triangle": typeof Triangle;
	"ValueAxis": typeof ValueAxis;
	"Venn": typeof Venn;
	"VerticalLayout": typeof VerticalLayout;
	"WordCloud": typeof WordCloud;
	"XYChart": typeof XYChart;
	"XYChartScrollbar": typeof XYChartScrollbar;
	"XYCursor": typeof XYCursor;
	"XYSeries": typeof XYSeries;
	"ZoomControl": typeof ZoomControl;
}

const classes: IClasses = {
	"Annotator": Annotator,
	"Axis": Axis,
	"AxisBullet": AxisBullet,
	"AxisLabel": AxisLabel,
	"AxisLabelRadial": AxisLabelRadial,
	"AxisRenderer": AxisRenderer,
	"AxisRendererCircular": AxisRendererCircular,
	"AxisRendererRadial": AxisRendererRadial,
	"AxisRendererX": AxisRendererX,
	"AxisRendererY": AxisRendererY,
	"AxisTick": AxisTick,
	"BaseColumnSeries": BaseColumnSeries,
	"BreadcrumbBar": BreadcrumbBar,
	"Bullet": Bullet,
	"Button": Button,
	"Candlestick": Candlestick,
	"CandlestickSeries": CandlestickSeries,
	"CategoryAxis": CategoryAxis,
	"CategoryDateAxis": CategoryDateAxis,
	"Chart": Chart,
	"Chord": Chord,
	"ChordDirected": ChordDirected,
	"ChordLink": ChordLink,
	"ChordLinkDirected": ChordLinkDirected,
	"ChordNodes": ChordNodes,
	"ChordNonRibbon": ChordNonRibbon,
	"Circle": Circle,
	"CirclePattern": CirclePattern,
	"ClockHand": ClockHand,
	"ColorSet": ColorSet,
	"ColumnSeries": ColumnSeries,
	"Component": Component,
	"Container": Container,
	"DateAxis": DateAxis,
	"DurationAxis": DurationAxis,
	"Ellipse": Ellipse,
	"Entity": Entity,
	"Exporting": Exporting,
	"ExportingMenu": ExportingMenu,
	"Flow": Flow,
	"FlowLink": FlowLink,
	"FlowNode": FlowNode,
	"FlowNodes": FlowNodes,
	"ForceDirected": ForceDirected,
	"FunnelSeries": FunnelSeries,
	"FunnelSlice": FunnelSlice,
	"GaplessDateAxis": GaplessDateAxis,
	"Gradient": Gradient,
	"Graphics": Graphics,
	"GraticuleSeries": GraticuleSeries,
	"Grid": Grid,
	"GridLayout": GridLayout,
	"HeatLegend": HeatLegend,
	"Hierarchy": Hierarchy,
	"HierarchyLink": HierarchyLink,
	"HierarchyNode": HierarchyNode,
	"HorizontalLayout": HorizontalLayout,
	"InterfaceColors": InterfaceColors,
	"Label": Label,
	"Layout": Layout,
	"Legend": Legend,
	"Line": Line,
	"LinePattern": LinePattern,
	"LineSeries": LineSeries,
	"LinearGradient": LinearGradient,
	"LinkedHierarchy": LinkedHierarchy,
	"LinkedHierarchyNode": LinkedHierarchyNode,
	"MapChart": MapChart,
	"MapLine": MapLine,
	"MapLineSeries": MapLineSeries,
	"MapPointSeries": MapPointSeries,
	"MapPolygon": MapPolygon,
	"MapPolygonSeries": MapPolygonSeries,
	"MapSeries": MapSeries,
	"Modal": Modal,
	"OHLC": OHLC,
	"OHLCSeries": OHLCSeries,
	"Pack": Pack,
	"Partition": Partition,
	"Pattern": Pattern,
	"PercentChart": PercentChart,
	"PercentSeries": PercentSeries,
	"PictorialStackedSeries": PictorialStackedSeries,
	"Picture": Picture,
	"PieChart": PieChart,
	"PieSeries": PieSeries,
	"PointedRectangle": PointedRectangle,
	"PyramidSeries": PyramidSeries,
	"RadarChart": RadarChart,
	"RadarColumnSeries": RadarColumnSeries,
	"RadarCursor": RadarCursor,
	"RadarLineSeries": RadarLineSeries,
	"RadialGradient": RadialGradient,
	"RadialLabel": RadialLabel,
	"RadialText": RadialText,
	"Rectangle": Rectangle,
	"RectanglePattern": RectanglePattern,
	"RoundedRectangle": RoundedRectangle,
	"Sankey": Sankey,
	"SankeyLink": SankeyLink,
	"SankeyNodes": SankeyNodes,
	"Scrollbar": Scrollbar,
	"SerialChart": SerialChart,
	"Series": Series,
	"Slice": Slice,
	"SliceGrouper": SliceGrouper,
	"SlicedChart": SlicedChart,
	"Slider": Slider,
	"SmoothedRadarLineSeries": SmoothedRadarLineSeries,
	"SmoothedXLineSeries": SmoothedXLineSeries,
	"SmoothedXYLineSeries": SmoothedXYLineSeries,
	"SmoothedYLineSeries": SmoothedYLineSeries,
	"Sprite": Sprite,
	"Star": Star,
	"StepLineSeries": StepLineSeries,
	"Sunburst": Sunburst,
	"Text": Text,
	"Tick": Tick,
	"Tooltip": Tooltip,
	"Tree": Tree,
	"Treemap": Treemap,
	"Triangle": Triangle,
	"ValueAxis": ValueAxis,
	"Venn": Venn,
	"VerticalLayout": VerticalLayout,
	"WordCloud": WordCloud,
	"XYChart": XYChart,
	"XYChartScrollbar": XYChartScrollbar,
	"XYCursor": XYCursor,
	"XYSeries": XYSeries,
	"ZoomControl": ZoomControl,
};

export default classes;
